version: "3.9"
services: 
  ascii:
    image: asciidoctor/docker-asciidoctor
    command: "asciidoctor-pdf -o ./target/sarch.pdf -v -r asciidoctor-bibtex -r asciidoctor-diagram ./src/docs/asciidoc/sarch.adoc"
    volumes:
      - ".:/documents"
  ascii-html:
    image: asciidoctor/docker-asciidoctor
    command: "./build-html.sh"
    volumes:
      - ".:/documents"
  