== Components

Component-based development is een oude techniek in Software Architectuur. In de basis kennen we de techniek al uit Object-Oriented Programming: onze code-base wordt makkelijker te begrijpen, en te onderhouden, als we er voor zorgen dat je niet ten aller tijden alle details in de gaten hoeft te houden. In OOP regelen we dit door een duidelijk onderscheid te maken tussen de public en private members (attributen en methoden) in een class. Zo kunnen we er voor zorgen dat een object van buitenaf 'lekker makkelijk' in het gebruik is, ongeacht hoe ingewikkeld het aan de binnenkant blijkt te zijnfootnote:[Blader bijv. eens door de sourcecode van de java.util.ArrayList<> class. In IntelliJ kun je gewoon rechtsklikken op de class en 'Go to Implementation' aanklikken.].

Componenten passen precies ditzelfde idee toe, maar dan een leveltje hoger. Een component is een groep classes (en interfaces, en enums, etc.), waarvan sommige classes bedoeld zijn voor publiek gebruik, die je van buiten de component kan aanroepen, maar ook dat er classes zijn waarbij dat niet de bedoeling is, de private binnenkant. De classes die bedoeld zijn voor publieke consumptie worden (nogal verwarrend) ook wel de 'interface' of het 'contract' van de component genoemd. Deze notie van een interface bestaat ook in UML, dus we hebben de vreemde situatie dat een UML-interface uit Java-interfaces en classes kan bestaan, en een java-interface bestaat dan juist weer alleen uit methods. Uiteindelijk gaat het dus om de betekenis van het woord 'interface' als 'buitenste laagje'.

Deze truuk van information-hiding kan je uiteraard ook op hoger liggende niveaus toepassen; publieke en private componenten binnen een service, publieke en private services binnen een systeem, publieke en private systemen binnen een landschap, etc. (al lopen we wel tegen de grenzen van de standaard-terminologie aan).

Kortom het gaat om goede encapsulatie, en dat geeft componenten een aantal prettige architecturele eigenschappen:

* Een goede component is autonoom. Een component kan in z'n eentje kan iets nuttigs, of voegt in elk geval iets wezenlijks toe aan het grotere geheel. 
* Een goede component is modulair. Ze hebben een duidelijk contract, en kunnen gecombineerd en hergebruikt worden om grotere problemen op te lossen.
* Een goede component is vervangbaar. Omdat de buitenkant (de interface) van de component helder gedefiniëerd is, kan iemand anders relatief makkelijk een eigen versie maken.

Een hele eenvoudige manier om die encapsulatie te bewerkstelligen is om als de functionaliteit van de component af is, één class aan te maken die als aanspreekpunt voor de hele component dient. Die class noemen we dan een Facade (Faccia is Italiaans voor gezicht, façade is Frans voor voorhoofd). Uiteraard hebben we bij <<dependencies>> geleerd dat je in dit soort gevallen even moet oppassen, want als iemand een Dependency neemt op de Facade, dan neem je ook een Dependency op alle parameters en return-types in publieke methodes. Mocht daar iets tussen zitten dat je liever niet blootstelt, dan is het een goed idee om een speciaal 'alleen-lezen' versie van dat objectje te maken, puur ter uitwisseling van gegevens: een DTO (Data-Transfer-Object).

De aanwezigheid van een Facade is niet verplicht voor een component, de essentie is de duidelijke scheiding tussen binnen, en buitenkant. In Java kun je dat bewerkstelligen door de classes in de 'interface' public te maken, en de overige classes package-private (door niets, ook geen private of protected, voor de class te zetten). Een andere, modernere manier om components in Java te maken vind je in het Java Module System (wat ook een verwarrende naam is, omdat module zoveel verschillende dingen kan betekenen). Met het Java Module System (ook wel Jigsaw) genoemd, kan je per Java .jar aangeven welke classes van buitenaf gebruikt mogen worden, en welke niet. JavaFX maakt hier vrij enthousiast gebruik van.

=== Logisch vs. Fysiek

Een logisch componenten model is één van de meest intuïtieve manieren om je applicatie onder te verdelen. Op logisch niveau laten we veel detail weg, en focussen we puur op welke grove groepen functionaliteit we in de applicatie willen realiseren. Een simpel winkelvoorbeeld kan bijv. bestaan uit:

[plantuml,"logical-components",svg]
.Voorbeeld logisch componentenmodel
----
skinparam classAttributeIconSize 0
skinparam packageStyle folder

package verkoop {
    package bezorging #ffffff {}
}

package assortiment { 
    package aanbiedingen #ffffff {}   
}

package voorraad #ffffff {
}

verkoop ..> assortiment
voorraad ..> assortiment
verkoop ..> voorraad
----

Met een diagram als dit kun je dan bijv. dubbelchecken of je alle belangrijke functionaliteit onderverdeeld hebt, of kun je beginnen met het werk verdelen tussen projectleden op school, of teams van developers in een bedrijf. Het is prettig als je geen circulaire dependencies tussen je componenten hebt, dat geeft rust in je ontwerp. Als er geen cirkels zijn, dan is er ergens een stabiel punt (in dit voorbeeld 'assortiment') wat op een gegeven moment echt 'af genoeg' kan zijn; en dat plant een stuk makkelijker. 

Helaas is dit niet altijd mogelijk, stel het is bijv. heel erg belangrijk dat afhankelijk van de bezorgingen extra producten in bepaalde regios in de aanbieding komen ("want we gingen toch al met een vrachtwagen vol die kant op..."), dan is er waarschijnlijk plotseling een Dependency van aanbieding naar bezorging. De aanbiedingen component moet immers aan de bezorging component kunnen vragen waar er allemaal bezorgd gaat worden. Dan zullen de teams van die twee onderdelen constant bij elkaar een vinger aan de pols moeten houden of ze elkaar niet per ongeluk in de weg zitten. Het kan immers voorkomen dat één van de teams denkt alles op orde te hebben, maar helaas, een last-minute change van de ander gooit roet in het eten, en een iteratie later vice-versa. Een alternatieve optie is om te gaan uitzoeken of de hele 'aanbiedingen'-module niet beter thuis hoort in 'verkoop' voor deze applicatie. Puur op basis van intuïtie zou zo'n module zowel in assortiment of in verkoop prima thuis horen, maar op basis van de componenten-structuur hebben we nu een mogelijke concrete reden om 'm te verplaatsen. Een reden om dat niet te doen zou bijv. zijn als het teveel werk wordt om bij te houden voor het team van 'Verkoop', of omdat de business-expertise over aanbiedingen allemaal in dit specifieke bedrijf aanwezig zijn bij de mensen van 'assortiment'.

Kortom, er is niet een objectief goed of fout voor 'het algemene geval'. Er zijn principes, zoals het idealiter vermijden van circulaire component-dependencies, en die zorgen er voor dat je bepaalde opties als architect wel, of juist niet, overweegt.

Een logisch model is natuurlijk niet puur een paar 'boxes & lines', die vormen alleen maar een diagram. Het model is een mentaal construct, en in dat mentale construct horen dus ook de _dingen_ (classes, functies, verantwoordelijkheden etc.) die je in die boxes zou willen stoppen! Dus een model is pas volledig als je niet alleen de structuur helder hebt, maar ook *wat* je met die structuur wil bereiken.

Afhankelijk van je doelpubliek dien je dit duidelijk te documenteren. Sommige lezers (bijv. collega architecten of programmeurs) zullen erg geholpen zijn met een illustratie van het soort domein-classes of methods dat je in de component wilt beleggen. Anderen (minder technische lezers) zullen juist een alinea tekst waarderen waarin je uitlegt wat voor usecases en data er in een component thuis horen. In weer andere situaties (kleine teams, ervaren programmeurs, ICTers als managers, of echt super-super-duidelijke namen en domeinen) kunnen zelfs puur de 'boxes & lines' voldoende zijn. Het gaat erom dat je het model in je hoofd zo goed mogelijk kan overbrengen op de lezer.

Op fysiek niveau schakelen we over van planning naar daadwerkelijke implementatie in code. Dan moeten we explicieter zijn wat exact onze interface is en daar willen we preciezer zijn over exact welke classes er private zijn in de component. Aangezien we dan toch al in detail aan het treden zijn is het vaak ook een prima moment om bepaalde code-structuren of design-patterns in te zetten.

[plantuml,"physical-components",svg]
.Voorbeeld fysiek componentenmodel
----
component verkoop {
    class Verkoop
    class Klant
    package bezorging #ffffff {
        class Bezorging
        class Route
    }
}

component assortiment { 
    class Product
    package aanbiedingen #ffffff {
        class Aanbieding
        class Periode
    }   
}

component voorraad #ffffff {
    class Product {
        +aantalInVoorraad: int
    }
    class Levering {

    }
}
----

In dit fysieke model zie je dat er 

****
Persoonlijk heb ik in m'n werkzame leven nooit gedetaileerde 'fysieke' modellen getekend. Als we met het team op dat niveau aan het nadenken waren was het meestal sneller om het gelijk ook in code uit te werken (of het was ietsje langzamer, maar dan had je daarna tenminste ook echt het product). Als je dit interessant vindt dan moet je eens naar https://www.agilealliance.org/resources/experience-reports/mob-programming-agile2014/[Mob-Programming] kijken.

Grappig genoeg ben ik pas fysieke, gedetaileerde modellen gaan gebruiken als docent! Dit gebeurde vooral als ik een idee wou uitleggen aan een team studenten die werkten in een programmeertaal die ik zelf (nog) niet sprak (C, C++ en Rust staan allemaal nog op de 'todo'-list, maar die ken ik nog niet).

Kortom, toen viel voor mij het kwartje waarom sommige architecten de voorkeur geven aan gedetailleerde modellen. De modellen zijn tricky te schrijven (want geen compiler, geen unit-tests, geen goede IDE), maar ze zijn behoorlijk intuïtief, zonder veel training, te lezen voor bijna alle programmeurs. En als architecten zijn we communicators first: als wij een beetje extra moeite moeten doen, om het voor onze lezers makkelijk te maken... dan doen we dat maar.

-Tom
****
=== Coupling en Cohesion

Een ander perspectief op het bouwen van classes, en wederom gaat die theorie 1-1 mee naar components, is om te kijken naar de Coupling en Cohesion eigenschappen. Coupling hebben we al enigszins besproken in <<coupling>>. Binnen de context van componenten is één van de belangrijkste punten om op te letten is dat je heel erg oppast met coupling aangaan met andere componenten. Hoe meer de classes in jouw component een andere component nodig hebben, hoe moeilijker het gaat worden om jouw component te hergebruiken. Helemaal opvallend is als onderdelen van jouw component _meer_ dependencies buiten de component dan binnen de component hebben, dan zit die class waarschijnlijk op de verkeerde plek.

Een ander onderdeel is 'cohesie'. Als er classes in je component zitten die niet gebruikt worden door de rest, dan is dat vreemd. Waarom zitten ze dan in je component? Dan is het beter om ze eruit te halen, want dan hebben evt. dependencies op die class niet direct een dependency op de hele component! Vanuit dezelfde gedachte is het ook goed om te kijken of je geen 'eilandjes' in je componenten hebt zitten. Groepjes classes die elkaar wel nodig hebben, maar tussen de groepjes is geen samenwerking. In dat soort gevallen (en dat gebeurt regelmatig) heb je per ongeluk gewoon meerdere componenten in één gepropt. Het nadeel is wederom dat wanneer iemand van buiten één van die groepjes nodig heeft, dat je direct een koppeling op de hele component hebt.

Kort door de bocht zegt Cohesion dus dat je classes (en interfaces, en abstract classes etc.) elkaar 'voldoende' nodig moeten hebben. Want anders gaan ze maar mooi in hun eigen component wonen.

=== Trucs met componentenontwerp


